version: "3.9"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=image
      - POSTGRES_USER=image
      - POSTGRES_PASSWORD=image123


  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db:db




