# Generated by Django 3.2.9 on 2021-11-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaimage',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
