# Generated by Django 3.2.9 on 2021-11-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_mediaimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaimage',
            name='base64_image',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mediaimage',
            name='image',
            field=models.ImageField(upload_to='img'),
        ),
    ]
